# Generated by Django 3.1.2 on 2020-10-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('phone', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('profile_image', models.ImageField(upload_to='images/')),
                ('nickname', models.CharField(max_length=10)),
            ],
        ),
    ]
