# Generated by Django 3.1.2 on 2020-10-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pashion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
