# Generated by Django 3.0.10 on 2020-11-03 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pashion', '0005_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
