# Generated by Django 3.1.2 on 2020-11-03 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pashion', '0005_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
