# Generated by Django 3.1.2 on 2020-11-06 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0006_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('content', models.TextField()),
                ('like', models.IntegerField(default=0)),
                ('read', models.IntegerField(default=0)),
                ('create_day', models.DateTimeField(auto_now_add=True)),
                ('update_day', models.DateTimeField(auto_now=True)),
                ('style_tag', models.TextField(blank=True, null=True)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='DailyReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_day', models.DateTimeField(auto_now_add=True)),
                ('update_day', models.DateTimeField(auto_now=True)),
                ('ref', models.IntegerField()),
                ('ref_num', models.IntegerField()),
                ('daily_id', models.ForeignKey(db_column='daily_id', on_delete=django.db.models.deletion.CASCADE, to='daily.daily')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='DailyLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_id', models.ForeignKey(db_column='daily_id', on_delete=django.db.models.deletion.CASCADE, to='daily.daily')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_id', models.ForeignKey(db_column='daily_id', on_delete=django.db.models.deletion.CASCADE, to='daily.daily')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
