# Generated by Django 3.1.2 on 2020-11-03 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daily',
            old_name='user_id',
            new_name='user',
        ),
    ]
