# Generated by Django 3.1.2 on 2020-11-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0002_remove_daily_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreply',
            name='ref_num',
            field=models.IntegerField(default=1),
        ),
    ]
