# Generated by Django 3.0.10 on 2020-11-03 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20201103_1036'),
        ('daily', '0002_auto_20201103_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daily',
            name='user',
        ),
        migrations.AddField(
            model_name='daily',
            name='user_id',
            field=models.ForeignKey(default='admin', on_delete=django.db.models.deletion.CASCADE, to='user.User'),
            preserve_default=False,
        ),
    ]
