# Generated by Django 3.1.2 on 2020-11-04 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_delete_profile'),
        ('daily', '0004_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='daily_id',
            field=models.ForeignKey(db_column='daily_id', on_delete=django.db.models.deletion.CASCADE, to='daily.daily'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AlterField(
            model_name='daily',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
