# Generated by Django 3.1.2 on 2020-11-04 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_delete_profile'),
        ('daily', '0005_auto_20201104_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_id', models.ForeignKey(db_column='daily_id', on_delete=django.db.models.deletion.CASCADE, to='daily.daily')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
