# Generated by Django 3.1.2 on 2020-11-05 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0006_dailylike'),
        ('daily', '0003_auto_20201103_1749'),
    ]

    operations = [
    ]
