# Generated by Django 3.1.2 on 2020-10-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=15)),
                ('newpassword', models.CharField(max_length=15)),
                ('create_day', models.DateTimeField(auto_now_add=True)),
                ('update_day', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('profile_image', models.ImageField(null=True, upload_to='images/')),
                ('nickname', models.CharField(max_length=10)),
                ('description', models.TextField(null=True)),
                ('like_style', models.TextField(null=True)),
            ],
        ),
    ]
