# Generated by Django 3.1.2 on 2020-10-23 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201023_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='newpassword',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password_chk',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
