# Generated by Django 3.1.2 on 2020-11-03 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20201103_1036'),
        ('user', '0004_profile'),
    ]

    operations = [
    ]
