# Generated by Django 3.1.2 on 2020-11-03 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_merge_20201103_1623'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
