# Generated by Django 3.1.2 on 2020-11-04 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='profile_image',
        ),
    ]
