# Generated by Django 3.1.2 on 2020-11-07 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20201104_2256'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
